
spring:
  security:
    oauth2:
      client:
        registration:
          public-client:
            provider: spring
            client-id: public-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: public-client
          public-client-authorization-code:
            provider: spring
            client-id: public-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/authorized"
            scope: public.read
            client-name: public-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000