#spring.security.oauth2.client.registration.bael.client-name=bael
#spring.security.oauth2.client.registration.bael.client-id=public-client
#spring.security.oauth2.client.registration.bael.client-secret=secret
#spring.security.oauth2.client.registration.bael.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.bael.redirect-uri=http://127.0.0.1:8080/login/oauth2/code/public-client
#
#spring.security.oauth2.client.provider.bael.token-uri=http://localhost:9000/oauth/token
#spring.security.oauth2.client.provider.bael.authorization-uri=http://localhost:9000/oauth/authorize
#spring.security.oauth2.client.provider.bael.user-info-uri=http://localhost:9000/user
#spring.security.oauth2.client.provider.bael.user-name-attribute=name
#spring.security.oauth2.provider.bael.issuer-uri=http://auth-server:9000
spring:
  security:
    oauth2:
      client:
        registration:
          public-client:
            provider: spring
            client-id: public-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: public-client
          public-client-authorization-code:
            provider: spring
            client-id: public-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: public.read
            client-name: public-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000